language: python

cache: pip

services:
  - redis-server

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"

install:
  - pip install coveralls
  - pip install codecov
  - pip install .
  - cp travis_config/uwhoisd.ini extra/uwhoisd.ini
  - pushd client
  - python setup.py install
  - popd

script:
  - coverage run --source=uwhoisd uwhoisd/__init__.py extra/uwhoisd.ini &
  - sleep 15
  - nosetests --with-coverage --cover-package=uwhoisd
  - coverage combine .coverage*

after_success:
  - codecov
  - coveralls
