language: python
cache: pip
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
install:
  - pip install -r requirements-test.txt
before_script:
  - flake8 uwhoisd
  - flake8 --ignore=D100,D101,D102,D103,D104,D200 tests setup.py
script:
  - py.test --doctest-modules uwhoisd tests
