language: python

cache: pip

python:
  - '3.6'
  - '3.6-dev'
  - '3.7-dev'
  - "nightly"

install:
  - pip install pipenv
  # install redis
  - pushd ..
  - git clone https://github.com/antirez/redis.git
  - pushd redis
  - make
  - popd
  - popd
  - pipenv install -d
  - echo UWHOISD_HOME="'`pwd`'" > .env

script:
  - pipenv run start.py
  - sleep 5
  - nosetests --with-coverage --cover-package=uwhoisd
  - coverage combine .coverage*

after_success:
  - codecov
  - coveralls
