language: python

cache: pip

services:
  - redis-server

python:
  - '3.6'
  - '3.6-dev'
  - '3.7-dev'
  - "nightly"

install:
  - pip install coveralls codecov
  - pip install -r requirements.txt
  - pip install .
  - pushd client
  - pip install .
  - popd

script:
  - uwhoisd -c extra/uwhoisd.ini &
  - pid=$!
  - sleep 5
  - nosetests --with-coverage --cover-package=uwhoisd
  - kill -s INT $pid
  - coverage combine .coverage*

after_success:
  - codecov
  - coveralls
