language: python

cache: pip

python:
  - '3.6'
  - '3.6-dev'
  - '3.7-dev'
  - "nightly"

install:
  - pip install coveralls codecov
  - pip install -r requirements.txt
  - pip install -e .
  - pushd client
  - pip install -e .
  - popd
  - cd ..
  - git clone https://github.com/antirez/redis.git
  - cd redis
  - make
  - cd $TRAVIS_BUILD_DIR

script:
  - export UWHOISD_HOME=$TRAVIS_BUILD_DIR
  - run_backend.py --start
  - uwhoisd -c extra/uwhoisd.ini &
  - pid=$!
  - sleep 5
  - nosetests --with-coverage --cover-package=uwhoisd
  - kill -s INT $pid
  - coverage combine .coverage*

after_success:
  - codecov
  - coveralls
